### ISSUE TITLE
请问，要怎么才能部署到https协议的域名上呢

### ISSUE THREAD

**Issue by beimingxinglian** [fslongjin/My-Easy-Pic-Bed#1]
服务器的域名是https，请问要怎么才能通过https访问图床，http会被转到https上

**Comment by fslongjin** [comment]
Hello, to deploy my-easy-pic-bed with HTTPS protocol to the server, you need to configure the reverse proxy of nginx and set the SSL Certificate in nginx. Thank you.
Because of his is not part of this project, so the issue will be closed.

您好，使用https部署到服务器上需要您自行配置nginx的反向代理并在nginx中设置ssl证书，谢谢。这并不属于本项目的内容，因此问题将被关闭
